# Generated by Django 4.0.4 on 2022-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_character_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
